import sqlite3
con=sqlite3.connect('sybcaj.db')
cur=con.cursor()
print('connected sqlite3')
'''
cur.execute("create table emp(id,name,city);")
print('table created')cur.execute("insert into emp values(101,'vimal','surat')")
print('1')
cur.execute("insert into emp values(101,'vimal','surat')")
print('1')
cur.execute("insert into emp values(102,'jagdish','vapi')")
print('2')
cur.execute("insert into emp values(103,'aakash','baroda')")
print('3')
cur.execute("insert into emp values(104,'jatin','rajkot')")
print('4')
cur.execute("insert into emp values(105,'vivek','rajkot')")
print('5')
cur.execute("insert into emp values(106,'manish','surat')")
print('6')
cur.execute("insert into emp values(107,'gopal','surat')")
print('7')
cur.execute("insert into emp values(108,'yogesh','baroda')")
print('8')
cur.execute("insert into emp values(109,'vikas','vapi')")
print('9')
cur.execute("insert into emp values(110,'dipak','vapi')")
print('10')'''
cur.execute("select * from emp where name like 'j%';")
data=cur.fetchall()
print(data)
for i in data:
	print (i)
con.commit()

